# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Windows build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pyinstaller
        
    - name: Build .exe
      run: set PYTHONOPTIMIZE=1 && pyinstaller --onefile makejxl.py

    # - name: Run UPX
    #   uses: crazy-max/ghaction-upx@v1
    #   with:
    #     version: latest
    #     file: ./dist/ExifDateTool.exe
    #     args: --best

    - name: Archive exe file
      uses: actions/upload-artifact@v2
      with:
        name: exe-file
        path: ./dist/makejxl.exe



